DELETE http://localhost:8080/api/blogs/64c35f8cc2613a5e8d9931f4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkZXBlIiwiaWQiOiI2NGMxZjkyMjUzY2NkNjFlZWNlZjc0OTAiLCJpYXQiOjE2OTA3ODA4MTMsImV4cCI6MTY5MDc4NDQxM30.P2Kkc-bb9n6oAtACPM2lAOXXP_F53HJJB6MNQRXoI9E