# fly.toml app configuration file generated for test-phonebook on 2023-07-10T12:45:11+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "test-phonebook"
primary_region = "ams"

[env]
  PORT = "8080" # add this

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
